# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170704_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edgarcompanyinfo',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='edgardocumentcontent',
            options={'verbose_name_plural': 'Document Content'},
        ),
        migrations.AlterModelOptions(
            name='edgarsdfiling',
            options={'verbose_name_plural': 'SD Filings'},
        ),
        migrations.AlterModelOptions(
            name='edgarsdfilingdocument',
            options={'verbose_name_plural': 'SD Filing Documents'},
        ),
        migrations.AlterModelOptions(
            name='edgarsearch',
            options={'verbose_name_plural': 'Edgar Requests'},
        ),
    ]
