# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgarCompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(blank=True, max_length=200)),
                ('conformed_name', models.CharField(blank=True, max_length=200)),
                ('ticker_symbol', models.CharField(blank=True, max_length=10)),
                ('sic_code', models.CharField(blank=True, max_length=200)),
                ('sic_description', models.CharField(blank=True, max_length=200)),
                ('state_location', models.CharField(blank=True, max_length=10)),
                ('state_of_incorporation', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='EdgarDocumentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.BinaryField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Document Content',
            },
        ),
        migrations.CreateModel(
            name='EdgarSDFiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accepted', models.DateTimeField()),
                ('n_documents', models.PositiveIntegerField()),
                ('sec_accession_number', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edgar.EdgarCompanyInfo')),
            ],
            options={
                'verbose_name_plural': 'SD Filings',
            },
        ),
        migrations.CreateModel(
            name='EdgarSDFilingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('doc_size', models.PositiveIntegerField()),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_url', models.TextField()),
                ('doc_format', models.CharField(max_length=10)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edgar.EdgarSDFiling')),
            ],
            options={
                'verbose_name_plural': 'SD Filing Documents',
            },
        ),
        migrations.CreateModel(
            name='EdgarSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the request.')),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('date_accessed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Edgar Requests',
            },
        ),
        migrations.AddField(
            model_name='edgardocumentcontent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edgar.EdgarSDFilingDocument'),
        ),
    ]
