# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0003_auto_20170706_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgarsdfiling',
            name='n_documents',
        ),
        migrations.AlterField(
            model_name='edgarsdfiling',
            name='accepted',
            field=models.DateTimeField(blank=True, help_text='Accepted Date', null=True),
        ),
        migrations.AlterField(
            model_name='edgarsdfiling',
            name='date',
            field=models.DateField(blank=True, help_text='Filing Date', null=True),
        ),
    ]
