# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0005_auto_20170706_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgarsdfiling',
            name='filing_type',
            field=models.CharField(choices=[('SD', 'SD'), ('SD/A', 'SD/A')], default='SD', max_length=10),
            preserve_default=False,
        ),
    ]
